// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function CopyProject(arg1:string,arg2:string):Promise<string>;

export function DeleteMessage(arg1:string,arg2:string,arg3:string):Promise<void>;

export function DeleteProject(arg1:string):Promise<void>;

export function DeleteSession(arg1:string,arg2:string):Promise<void>;

export function EscapeProjectPath(arg1:string):Promise<string>;

export function GetClaudeDir():Promise<string>;

export function GetMessageRaw(arg1:string,arg2:string,arg3:string):Promise<models.JSONLEntry>;

export function GetMessages(arg1:string,arg2:string):Promise<Array<models.DisplayMessage>>;

export function GetProjectSessions(arg1:string):Promise<Array<string>>;

export function GetProjects():Promise<Array<models.ProjectInfo>>;

export function RenameProject(arg1:string,arg2:string):Promise<string>;

export function SaveMessages(arg1:string,arg2:string,arg3:Array<models.JSONLEntry>):Promise<void>;

export function SearchAcrossProjects(arg1:string,arg2:boolean,arg3:number):Promise<Array<models.SearchResult>>;

export function SearchInSession(arg1:string,arg2:string,arg3:string,arg4:boolean,arg5:number):Promise<Array<models.SearchResult>>;

export function UnescapeProjectName(arg1:string):Promise<string>;

export function UpdateMessageText(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;
