// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CopyProject(arg1, arg2) {
  return window['go']['main']['App']['CopyProject'](arg1, arg2);
}

export function DeleteMessage(arg1, arg2, arg3) {
  return window['go']['main']['App']['DeleteMessage'](arg1, arg2, arg3);
}

export function DeleteMessages(arg1, arg2, arg3) {
  return window['go']['main']['App']['DeleteMessages'](arg1, arg2, arg3);
}

export function DeleteProject(arg1) {
  return window['go']['main']['App']['DeleteProject'](arg1);
}

export function DeleteSession(arg1, arg2) {
  return window['go']['main']['App']['DeleteSession'](arg1, arg2);
}

export function EscapeProjectPath(arg1) {
  return window['go']['main']['App']['EscapeProjectPath'](arg1);
}

export function GetClaudeDir() {
  return window['go']['main']['App']['GetClaudeDir']();
}

export function GetMessageRaw(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetMessageRaw'](arg1, arg2, arg3);
}

export function GetMessages(arg1, arg2) {
  return window['go']['main']['App']['GetMessages'](arg1, arg2);
}

export function GetProjectSessions(arg1) {
  return window['go']['main']['App']['GetProjectSessions'](arg1);
}

export function GetProjects() {
  return window['go']['main']['App']['GetProjects']();
}

export function RenameProject(arg1, arg2) {
  return window['go']['main']['App']['RenameProject'](arg1, arg2);
}

export function SaveMessages(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveMessages'](arg1, arg2, arg3);
}

export function SearchAcrossProjects(arg1, arg2, arg3) {
  return window['go']['main']['App']['SearchAcrossProjects'](arg1, arg2, arg3);
}

export function SearchInSession(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['SearchInSession'](arg1, arg2, arg3, arg4, arg5);
}

export function UnescapeProjectName(arg1) {
  return window['go']['main']['App']['UnescapeProjectName'](arg1);
}

export function UpdateMessageText(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UpdateMessageText'](arg1, arg2, arg3, arg4);
}
